#!/usr/bin/env python3
"""
Regenerate bloom-vt's UAX #11 (East Asian Width) and UAX #29 (Grapheme
Cluster Boundary) interval tables from the Unicode Character Database.

Inputs (download from https://www.unicode.org/Public/UCD/latest/ucd/):
    EastAsianWidth.txt
    auxiliary/GraphemeBreakProperty.txt
    emoji/emoji-data.txt
    DerivedCoreProperties.txt   (for Default_Ignorable_Code_Point)

Output:
    src/bloom_vt/unicode_tables.c — replaces the hand-coded WIDE / ZERO
    interval lists currently embedded in width.c.

Usage:
    python3 gen_unicode_tables.py /path/to/UCD/dir > unicode_tables.c

The script intentionally has no third-party dependencies. Rerun when the
target Unicode version changes; commit the regenerated file.
"""

from __future__ import annotations
import os
import re
import sys
from collections import defaultdict
from typing import Iterable

CP_RANGE = re.compile(r"^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([^#\s]+)")


def parse_props(path: str) -> dict[str, list[tuple[int, int]]]:
    """Parse a UCD-format property file into {prop: [(lo, hi), ...]}."""
    out: dict[str, list[tuple[int, int]]] = defaultdict(list)
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = CP_RANGE.match(line)
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            out[m.group(3)].append((lo, hi))
    return out


def coalesce(ranges: Iterable[tuple[int, int]]) -> list[tuple[int, int]]:
    """Sort + merge adjacent/overlapping ranges."""
    items = sorted(ranges)
    out: list[tuple[int, int]] = []
    for lo, hi in items:
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def emit_table(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [f"static const Range {name}[] = {{"]
    for lo, hi in ranges:
        lines.append(f"    {{0x{lo:04X}, 0x{hi:04X}}},")
    lines.append("};")
    lines.append(f"#define {name}_LEN ((sizeof({name})/sizeof(({name})[0])))")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    ucd = argv[1]
    eaw = parse_props(os.path.join(ucd, "EastAsianWidth.txt"))
    gbp = parse_props(os.path.join(ucd, "auxiliary", "GraphemeBreakProperty.txt"))
    emo = parse_props(os.path.join(ucd, "emoji", "emoji-data.txt"))
    dcp = parse_props(os.path.join(ucd, "DerivedCoreProperties.txt"))

    wide = coalesce(eaw.get("W", []) + eaw.get("F", []))
    ambiguous = coalesce(eaw.get("A", []))

    # Zero-width = Extend ∪ Format ∪ Default_Ignorable_Code_Point
    zero = coalesce(
        gbp.get("Extend", [])
        + gbp.get("Control", [])
        + gbp.get("ZWJ", [])
        + dcp.get("Default_Ignorable_Code_Point", [])
    )

    # GCB classes for the runtime grapheme-break decision.
    extend = coalesce(gbp.get("Extend", []) + gbp.get("ZWJ", []))
    spacing_mark = coalesce(gbp.get("SpacingMark", []))
    prepend = coalesce(gbp.get("Prepend", []))
    extended_pictographic = coalesce(emo.get("Extended_Pictographic", []))

    print("/* Generated by gen_unicode_tables.py — do not edit by hand. */")
    print("#include \"bloom_vt_internal.h\"")
    print()
    print("typedef struct { uint32_t lo, hi; } Range;")
    print()
    print(emit_table("BVT_WIDE", wide))
    print()
    print(emit_table("BVT_AMBIGUOUS", ambiguous))
    print()
    print(emit_table("BVT_ZERO", zero))
    print()
    print(emit_table("BVT_EXTEND", extend))
    print()
    print(emit_table("BVT_SPACING_MARK", spacing_mark))
    print()
    print(emit_table("BVT_PREPEND", prepend))
    print()
    print(emit_table("BVT_EXT_PICT", extended_pictographic))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
